import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,realpath,rm,readFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {ApiClient} from '../../src/api/client.js';
import {CommerceAdapter,decimal} from '../../src/domains/commerce.js';
import {PlanEngine} from '../../src/planning/engine.js';
async function fixture(t:test.TestContext){
 const checkout=await realpath(await mkdtemp(path.join(os.tmpdir(),'asc-commerce-')));t.after(()=>rm(checkout,{recursive:true,force:true}));const root=path.join(checkout,'AppStore');await mkdir(root);await writeFile(path.join(root,'app.json'),JSON.stringify({schemaVersion:1,app:{appStoreId:'123',bundleId:'com.example.app',primaryLocale:'en-US'},platforms:['MAC_OS'],localizations:['en-US']}));
 const state={price:'0.00',schedule:true,future:false,override:false,failPost:false,unknownPost:false,available:true,futureTerritories:true,pointDuplicate:false,wrongPointParent:false};const calls:{url:string;method:string;body?:any}[]=[];
 const point=(id:string,amount:string)=>({id,type:'appPricePoints',attributes:{customerPrice:amount},relationships:{territory:{data:{id:'USA',type:'territories'}},app:{data:{id:state.wrongPointParent?'999':'123',type:'apps'}}}});
 const api=new ApiClient({token:()=> 'secret'},{readRetries:0,fetch:async(input,options)=>{
  const url=new URL(String(input));const method=options?.method??'GET';const body=options?.body?JSON.parse(String(options.body)):undefined;calls.push({url:url.pathname+url.search,method,body});
  if(method==='POST'){if(state.failPost)return Response.json({errors:[{code:'FORBIDDEN',detail:'secret'}]},{status:403});state.price=body.included[0].relationships.appPricePoint.data.id==='ZERO'?'0.00':'1.99';state.schedule=true;if(state.unknownPost)throw new Error('lost response');return Response.json({data:{id:'SCHEDULE',type:'appPriceSchedules'}},{status:201});}
  let data:unknown;let next:string|null=null;
  if(url.pathname==='/v1/apps/123')data={id:'123',type:'apps',attributes:{bundleId:'com.example.app'}};
  else if(url.pathname==='/v1/territories'){data=[{id:url.searchParams.has('cursor')?'DEU':'USA',type:'territories',attributes:{currency:url.searchParams.has('cursor')?'EUR':'USD'}}];if(!url.searchParams.has('cursor'))next='https://api.appstoreconnect.apple.com/v1/territories?cursor=2';}
  else if(url.pathname.endsWith('/appPriceSchedule')){if(!state.schedule)return new Response(null,{status:404});data={id:'SCHEDULE',type:'appPriceSchedules'};}
  else if(url.pathname.endsWith('/baseTerritory'))data={id:'USA',type:'territories'};
  else if(url.pathname.endsWith('/manualPrices'))data=[{id:'MANUAL',type:'appPrices',attributes:{startDate:state.future?'2999-01-01':null,endDate:null},relationships:{territory:{data:{id:'USA',type:'territories'}},appPricePoint:{data:{id:decimal(state.price)==='0'?'ZERO':'PAID',type:'appPricePoints'}}}},...(state.override?[{id:'OVERRIDE',type:'appPrices',attributes:{},relationships:{territory:{data:{id:'DEU',type:'territories'}},appPricePoint:{data:{id:'PAID-DEU',type:'appPricePoints'}}}}]:[])];
  else if(url.pathname.endsWith('/automaticPrices'))data=[];
  else if(url.pathname.startsWith('/v3/appPricePoints/'))data=point(url.pathname.split('/').at(-1)!,state.price);
  else if(url.pathname.endsWith('/appPricePoints'))data=[point('ZERO','0.00'),point('PAID','1.99'),...(state.pointDuplicate?[point('ZERO-2','0.00')]:[])];
  else if(url.pathname.endsWith('/appAvailabilityV2'))data={id:'AVAIL',type:'appAvailabilities',attributes:{availableInNewTerritories:state.futureTerritories}};
  else if(url.pathname.endsWith('/territoryAvailabilities'))data=['USA','DEU'].map(territory=>({id:'AVAIL-'+territory,type:'territoryAvailabilities',attributes:{available:territory==='USA'||state.available,contentStatuses:['AVAILABLE_FOR_SALE_UNRELEASED_APP']},relationships:{territory:{data:{id:territory,type:'territories'}}}}));
  else throw new Error('Unexpected route');return Response.json({data,links:{next}});
 }});
 const manifest=(value:unknown)=>writeFile(path.join(root,'commerce.json'),JSON.stringify({schemaVersion:1,...value as object}));
 const adapter=(domains:('price'|'availability')[]=['price','availability'])=>new CommerceAdapter({root,domains},[checkout],api,()=> 'account');const engine=new PlanEngine([checkout],true);const plan=()=>engine.create(adapter());const apply=(plan:any)=>engine.apply({planId:plan.planId,digest:plan.digest,operationIds:plan.operations.map((op:any)=>op.id),authorization:{confirmedByHost:true}});
 return {root,state,calls,manifest,adapter,engine,plan,apply};
}
test('decimal comparisons are exact and reject exponent, signs and binary coercion',()=>{assert.equal(decimal('000.000'),'0');assert.equal(decimal('12345678901234567890.1200'),'12345678901234567890.12');for(const value of ['NaN','-1','1e3','0x01','.5'])assert.throws(()=>decimal(value));});
test('missing commerce leaves an existing paid listing unmanaged',async t=>{const f=await fixture(t);f.state.price='1.99';assert.equal((await f.plan()).noOp,true);assert.equal(f.calls.filter(call=>call.method!=='GET').length,0);});
test('already free and all current territories is a transparent no-op including future behavior',async t=>{const f=await fixture(t);await f.manifest({price:{mode:'free',baseTerritory:'USA'},availability:{territories:'all',availableInNewTerritories:true}});const plan=await f.plan();assert.equal(plan.noOp,true);assert.equal((plan.summary as any).availabilityComparison.manualActionRequired,false);assert.deepEqual((plan.summary as any).availabilityComparison.requestedTerritories,['DEU','USA']);assert.ok(f.calls.some(call=>call.url.includes('cursor=2')));const artifact=JSON.parse(await readFile(plan.planPath as string,'utf8'));assert.deepEqual(artifact.summary,plan.summary);});
test('catalog-selected zero price is approved app-wide and uncertain POST is reconciled once',async t=>{const f=await fixture(t);f.state.price='1.99';f.state.unknownPost=true;await f.manifest({price:{mode:'free',baseTerritory:'USA'}});const plan=await f.plan();assert.equal((plan.operations as any[]).length,1);assert.match((plan.operations as any[])[0].scope,/APP-WIDE/);const result=await f.apply(plan);assert.equal(result.state,'complete');assert.equal(result.operations[0]!.state,'reconciled');assert.equal(f.calls.filter(call=>call.method==='POST').length,1);const body=f.calls.find(call=>call.method==='POST')!.body;assert.equal(body.included[0].relationships.appPricePoint.data.id,'ZERO');assert.equal(body.included[0].id,'${newprice-0}');assert.equal(body.included[0].id,body.data.relationships.manualPrices.data[0].id);assert.equal(body.included[0].attributes.startDate,null);assert.equal((await f.plan()).noOp,true);});
test('paid exact point supported; unavailable and ambiguous amounts rejected',async t=>{const f=await fixture(t);await f.manifest({price:{mode:'paid',baseTerritory:'USA',customerPrice:'1.99'}});assert.equal((await f.apply(await f.plan())).state,'complete');await f.manifest({price:{mode:'paid',baseTerritory:'USA',customerPrice:'1.98'}});await assert.rejects(f.plan(),/Exactly one/);await f.manifest({price:{mode:'free',baseTerritory:'USA'}});f.state.pointDuplicate=true;await assert.rejects(f.plan(),/Exactly one/);});
test('future schedules and territorial overrides cannot be silently overwritten',async t=>{const f=await fixture(t);f.state.price='1.99';await f.manifest({price:{mode:'free',baseTerritory:'USA'}});f.state.future=true;await assert.rejects(f.plan(),/future schedules/);f.state.future=false;f.state.override=true;await assert.rejects(f.plan(),/future schedules/);assert.equal(f.calls.filter(call=>call.method==='POST').length,0);});
test('availability additions/removals and future flags are manual; no availability write route is enabled',async t=>{const f=await fixture(t);f.state.available=false;f.state.futureTerritories=false;await f.manifest({availability:{territories:'all',availableInNewTerritories:true}});const plan=await f.plan();assert.equal(plan.noOp,true);assert.equal((plan.summary as any).availabilityComparison.manualActionRequired,true);assert.deepEqual((plan.summary as any).availabilityComparison.additions,['DEU']);assert.equal((await f.apply(plan)).state,'complete');assert.equal(f.calls.filter(call=>call.method!=='GET').length,0);await f.manifest({availability:{territories:['DEU']}});assert.deepEqual(((await f.plan()).summary as any).availabilityComparison.removals,['USA']);});
test('stale schedules, forbidden writes, unknown territories and wrong point parents fail safely',async t=>{const f=await fixture(t);await f.manifest({price:{mode:'paid',baseTerritory:'USA',customerPrice:'1.99'}});const plan=await f.plan();f.state.future=true;await assert.rejects(f.apply(plan),/changed/);f.state.future=false;f.state.failPost=true;const result=await f.apply(await f.plan());assert.equal(result.state,'partial');assert.equal(result.operations[0]!.state,'failed');await f.manifest({availability:{territories:['XXX']}});await assert.rejects(f.plan(),/current territory/);await f.manifest({price:{mode:'free',baseTerritory:'USA'}});f.state.wrongPointParent=true;await assert.rejects(f.plan(),/another app|requested app/);});
