import {createHash} from 'node:crypto';
import {realpath} from 'node:fs/promises';
import {z} from 'zod';
import type {ApiClient,ApiDocument} from '../api/client.js';
import {Discovery,resource,type StoreState} from '../api/resources/discovery.js';
import {editableVersionStates} from '../api/resources/states.js';
import {AppStoreError} from '../errors.js';
import {validateRepository} from '../repository/validate.js';
import type {AppManifest} from '../repository/schemas.js';
import {CommerceAdapter} from './commerce.js';
import {MetadataAdapter} from './metadata.js';
import {canonical,type Adapter,type Snapshot,type Operation,type Json} from '../planning/model.js';

const platform=z.enum(['MAC_OS']);
const version=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/);
const id=z.string().regex(/^[A-Za-z0-9_-]{1,128}$/);
export const readinessSelection=z.object({root:z.string().min(1),platform,version,buildId:id}).strict();
const confirmations=z.object({privacyDeclarations:z.literal(true),ageRating:z.literal(true),agreementsAndRegionalObligations:z.literal(true),exportCompliance:z.literal(true)}).strict();
export const submissionSelection=readinessSelection.extend({manualConfirmations:confirmations}).strict();
type ReadinessSelection=z.infer<typeof readinessSelection>;
type SubmissionSelection=z.infer<typeof submissionSelection>;
export interface ReadinessCheck{name:string;status:'verified'|'blocked'|'manualVerificationRequired'|'notApplicable';evidence:Json;remediation?:string}
interface BuildState{id:string;buildNumber:string;processingState:string;expired:boolean;usesNonExemptEncryption:boolean|null;appId:string;platform:string;version:string}
interface ItemState{id:string;state:string;versionId:string|null}
interface ReviewState{id:string;platform:string;state:string;items:ItemState[]}
interface LocaleState{id:string;locale:string;desktopSets:{id:string;states:string[]}[]}
interface ReleaseState{appId:string;bundleId:string;versionId:string;versionState:string;releaseType:string;earliestReleaseDate:string|null;build:BuildState;currentBuildId:string|null;locales:LocaleState[];review:StoreState['review']|null;reviewDrift:boolean;submissions:ReviewState[];commerce:Json;commercePriceDrift:boolean;metadataDrift:string[];screenshotDrift:string[]}
interface ReleaseSnapshot extends Snapshot{checks:ReadinessCheck[];confirmations:SubmissionSelection['manualConfirmations']}
const knownSubmissionStates=new Set(['READY_FOR_REVIEW','WAITING_FOR_REVIEW','IN_REVIEW','UNRESOLVED_ISSUES','CANCELING','COMPLETING','COMPLETE']);
const knownItemStates=new Set(['READY_FOR_REVIEW','ACCEPTED','APPROVED','REJECTED','REMOVED']);
const releaseWarning=(release:ReleaseState)=>release.releaseType==='AFTER_APPROVAL'?'Apple approval may publish this version automatically.':release.releaseType==='SCHEDULED'?`Apple approval may publish this version on its configured schedule${release.earliestReleaseDate?` beginning ${release.earliestReleaseDate}`:''}.`:release.releaseType==='MANUAL'?'Apple approval retains manual release control.':'Release behavior is unavailable or unsupported.';
const relation=(raw:unknown,name:string,type:string):string|null=>{const data=(raw as {relationships?:Record<string,{data?:unknown}>}).relationships?.[name]?.data;if(data==null)return null;return resource({...data as object,attributes:{}},type,[]).id;};
const operationId=(action:string)=>'submission-'+createHash('sha256').update(action).digest('hex').slice(0,24);

function active(release:ReleaseState):{draft:ReviewState|null;submitted:ReviewState|null;conflict:string|null} {
  const relevant=release.submissions.filter(item=>item.platform===release.build.platform&&item.state!=='COMPLETE');const drafts=relevant.filter(item=>item.state==='READY_FOR_REVIEW');if(drafts.length>1)return {draft:null,submitted:null,conflict:'Multiple compatible draft submissions exist.'};
  const nonDraft=relevant.filter(item=>item.state!=='READY_FOR_REVIEW');const target=nonDraft.filter(item=>item.items.some(entry=>entry.versionId===release.versionId));if(target.length>1)return {draft:drafts[0]??null,submitted:null,conflict:'Multiple active submissions reference the exact version.'};
  if(nonDraft.some(item=>!item.items.some(entry=>entry.versionId===release.versionId)))return {draft:drafts[0]??null,submitted:target[0]??null,conflict:'Another active submission for this platform contains unrelated items.'};
  const draft=drafts[0]??null;if(draft&&draft.items.some(item=>item.versionId!==release.versionId))return {draft,submitted:target[0]??null,conflict:'The compatible draft contains unrelated items that would also be submitted.'};
  if(draft&&draft.items.some(item=>item.versionId===release.versionId&&item.state!=='READY_FOR_REVIEW'))return {draft,submitted:target[0]??null,conflict:'The exact draft item is not ready for review.'};
  return {draft,submitted:target[0]??null,conflict:null};
}
export function releaseReadinessChecks(local:{valid:boolean;diagnostics:{path:string;rule:string;severity:string}[];desired:Record<string,unknown>},app:AppManifest,release:ReleaseState):ReadinessCheck[] {
  const checks:ReadinessCheck[]=[];const add=(name:string,status:ReadinessCheck['status'],evidence:Json,remediation?:string)=>checks.push({name,status,evidence,...(remediation?{remediation}:{})});
  const errors=local.diagnostics.filter(item=>item.severity==='error');add('repository',local.valid?'verified':'blocked',{errorCount:errors.length,errors:errors.slice(0,100).map(item=>({path:item.path,rule:item.rule}))},local.valid?undefined:'Resolve selected release repository diagnostics.');
  const flow=active(release);const already=flow.submitted&&['WAITING_FOR_REVIEW','IN_REVIEW','COMPLETING','COMPLETE'].includes(flow.submitted.state);
  add('versionState',editableVersionStates.has(release.versionState)||!!already?'verified':'blocked',{versionId:release.versionId,state:release.versionState},'Select an editable version or inspect its existing submission.');
  add('build',release.build.processingState==='VALID'&&!release.build.expired?'verified':'blocked',{buildId:release.build.id,buildNumber:release.build.buildNumber,processingState:release.build.processingState,expired:release.build.expired,selectedOnVersion:release.currentBuildId===release.build.id},'Select an exact processed, unexpired build for the same app/platform/version.');
  const intended=new Set(app.localizations);const localeMap=new Map(release.locales.map(item=>[item.locale,item]));const missing=[...intended].filter(locale=>!localeMap.has(locale));add('localizations',missing.length?'blocked':'verified',{required:[...intended].sort(),missing},'Synchronize every declared release locale.');
  add('metadataSync',release.metadataDrift.length?'blocked':'verified',{differences:release.metadataDrift},'Synchronize the explicitly managed metadata before submission.');
  const screenshotProblems=[...intended].flatMap(locale=>{const item=localeMap.get(locale);const sets=item?.desktopSets??[];return sets.length!==1||sets[0]!.states.length===0||sets[0]!.states.some(state=>state!=='COMPLETE')?[{locale,setCount:sets.length,states:sets.flatMap(set=>set.states)}]:[];});add('screenshots',screenshotProblems.length||release.screenshotDrift.length?'blocked':'verified',{displayType:'APP_DESKTOP',problems:screenshotProblems,differences:release.screenshotDrift},'Supply genuine screenshots, synchronize their exact order and bytes, and wait for COMPLETE processing in each declared locale.');
  const review=release.review;const required=['contactFirstName','contactLastName','contactPhone','contactEmail'];const missingReview=required.filter(field=>!review?.presentFields.includes(field));if(review?.demoAccountRequired)for(const field of ['demoAccountName','demoAccountPassword'])if(!review.presentFields.includes(field))missingReview.push(field);add('reviewContact',review&&typeof review.demoAccountRequired==='boolean'&&!missingReview.length&&!release.reviewDrift?'verified':'blocked',{presentFields:review?.presentFields??[],demoAccountRequired:review?.demoAccountRequired??null,managedValuesMatch:!release.reviewDrift,missing:missingReview},'Synchronize explicitly managed review details and provide required contacts and demo credentials.');
  const commerce=release.commerce as unknown as {price?:{current?:unknown}|null;availability?:{territories?:{available:boolean;contentStatuses:string[]}[]}|null;availabilityComparison?:{manualActionRequired?:boolean}};const available=commerce.availability?.territories?.filter(item=>item.available)??[];const availabilityManual=commerce.availabilityComparison?.manualActionRequired??false;add('priceAndAvailability',commerce.price?.current&&available.length&&!release.commercePriceDrift&&!availabilityManual?'verified':'blocked',{hasCurrentPrice:!!commerce.price?.current,configuredTerritoryCount:available.length,managedPriceDiffers:release.commercePriceDrift,availabilityManualActionRequired:availabilityManual},'Synchronize the explicitly managed current base price, apply requested availability manually, and create a fresh readiness check.');
  const statuses=[...new Set(available.flatMap(item=>item.contentStatuses))].sort();add('distributionRestrictions',statuses.some(status=>status.startsWith('CANNOT_SELL'))?'manualVerificationRequired':'verified',{contentStatuses:statuses},'Resolve or confirm App Store Connect distribution restrictions; configured territories do not prove effective availability.');
  add('privacyDeclarations','manualVerificationRequired',{apiEvidence:'No audited privacy-declaration completeness endpoint is used.'},'Owner must verify App Privacy answers in App Store Connect.');
  add('ageRating','manualVerificationRequired',{apiEvidence:'No audited age-rating completeness endpoint is used.'},'Owner must verify the current age rating.');
  add('exportCompliance',release.build.usesNonExemptEncryption===false?'verified':'manualVerificationRequired',{usesNonExemptEncryption:release.build.usesNonExemptEncryption},'Owner must resolve export compliance for this exact build.');
  add('agreementsAndRegionalObligations','manualVerificationRequired',{inference:'No legal answer is inferred from metadata or source.'},'Owner must verify agreements, trader status and regional obligations.');
  add('activeSubmission',flow.conflict||flow.submitted?.state==='UNRESOLVED_ISSUES'||flow.submitted?.state==='CANCELING'?'blocked':'verified',{draftId:flow.draft?.id??null,submittedId:flow.submitted?.id??null,state:flow.submitted?.state??flow.draft?.state??null,conflict:flow.conflict},flow.conflict??(flow.submitted?'Resolve the current submission state before a new submission.':undefined));
  add('releaseBehavior',['MANUAL','AFTER_APPROVAL','SCHEDULED'].includes(release.releaseType)?'verified':'blocked',{releaseType:release.releaseType,earliestReleaseDate:release.earliestReleaseDate,warning:releaseWarning(release)},'Resolve the exact release behavior before submission.');
  add('reviewAcceptance','notApplicable',{guarantee:'Passing readiness cannot guarantee Apple review acceptance.'});return checks;
}

export class SubmissionReader {
  readonly discovery:Discovery;
  constructor(private readonly selection:ReadinessSelection,private readonly roots:readonly string[],private readonly api:ApiClient,identity:()=>string){this.discovery=new Discovery(api,identity);}
  async read(signal?:AbortSignal):Promise<{root:string;app:AppManifest;local:{valid:boolean;diagnostics:{path:string;rule:string;severity:string}[];hashes:Record<string,string>;secretFingerprint:string;desired:Record<string,unknown>;images:Record<string,{md5:string}>};release:ReleaseState;checks:ReadinessCheck[];credentialContext:string}>{
    const selected=readinessSelection.parse({root:this.selection.root,platform:this.selection.platform,version:this.selection.version,buildId:this.selection.buildId});const local=await validateRepository({root:selected.root,platform:'macOS',version:selected.version,domains:['appInfo','versionMetadata','version','review','screenshots','commerce']},this.roots,process.env,signal);const app=local.desired['app.json'] as AppManifest;if(!app?.app.appStoreId)throw new AppStoreError('appSelectionRequired','Readiness requires a verified App Store app ID in app.json.');
    const store=await this.discovery.state({appStoreId:app.app.appStoreId,bundleId:app.app.bundleId,platform:selected.platform,version:selected.version},signal);if(!store.version)throw new AppStoreError('versionNotFound','Select one exact existing App Store version.');
    const buildDoc=await this.api.request<ApiDocument>(`/v1/builds/${selected.buildId}`,signal?{signal}:{});const build=resource(buildDoc?.data,'builds',['version','processingState','expired','usesNonExemptEncryption']);if(build.id!==selected.buildId||typeof build.attributes.version!=='string'||typeof build.attributes.processingState!=='string'||typeof build.attributes.expired!=='boolean')throw new AppStoreError('incompleteSnapshot','Selected build metadata is incomplete.');
    const buildApp=resource((await this.api.request<ApiDocument>(`/v1/builds/${build.id}/app`,signal?{signal}:{}))?.data,'apps',[]);const pre=resource((await this.api.request<ApiDocument>(`/v1/builds/${build.id}/preReleaseVersion`,signal?{signal}:{}))?.data,'preReleaseVersions',['platform','version']);if(buildApp.id!==store.app.id||pre.attributes.platform!==selected.platform||pre.attributes.version!==selected.version)throw new AppStoreError('wrongBuild','Build must belong to the exact app, platform and marketing version.');
    let currentBuildId:string|null=null;try{currentBuildId=resource((await this.api.request<ApiDocument>(`/v1/appStoreVersions/${store.version.id}/build`,signal?{signal}:{}))?.data,'builds',[]).id;}catch(error){if(!(error instanceof AppStoreError&&error.status===404))throw error;}
    const submissionsRaw=await this.api.list<unknown>(`/v1/apps/${store.app.id}/reviewSubmissions`,signal);if(submissionsRaw.length>100)throw new AppStoreError('incompleteSnapshot','Review submission inventory exceeds its bounded limit.');const submissions:ReviewState[]=[];
    for(const raw of submissionsRaw){const item=resource(raw,'reviewSubmissions',['platform','state']);if(typeof item.attributes.platform!=='string'||typeof item.attributes.state!=='string'||!knownSubmissionStates.has(item.attributes.state))throw new AppStoreError('incompleteSnapshot','Review submission state is unknown.');const raws=await this.api.list<unknown>(`/v1/reviewSubmissions/${item.id}/items`,signal);if(raws.length>100)throw new AppStoreError('incompleteSnapshot','Review submission item inventory exceeds its limit.');const items=raws.map(raw=>{const entry=resource(raw,'reviewSubmissionItems',['state']);if(typeof entry.attributes.state!=='string'||!knownItemStates.has(entry.attributes.state))throw new AppStoreError('incompleteSnapshot','Review submission item state is unknown.');return {id:entry.id,state:entry.attributes.state,versionId:relation(raw,'appStoreVersion','appStoreVersions')};});if(new Set(items.map(entry=>entry.id)).size!==items.length)throw new AppStoreError('incompleteSnapshot','Duplicate review submission items.');submissions.push({id:item.id,platform:item.attributes.platform,state:item.attributes.state,items:items.sort((a,b)=>a.id.localeCompare(b.id,'en'))});}
    if(new Set(submissions.map(item=>item.id)).size!==submissions.length)throw new AppStoreError('incompleteSnapshot','Duplicate review submissions.');
    const commerceAdapter=new CommerceAdapter({root:selected.root,domains:['price','availability']},this.roots,this.api,()=>store.credentialContext);const commerceSnapshot=await commerceAdapter.capture(signal);const locales=store.versionLocalizations.map(localization=>({id:localization.id,locale:String(localization.attributes.locale),desktopSets:(store.screenshotSets[localization.id]??[]).filter(set=>set.resource.attributes.screenshotDisplayType==='APP_DESKTOP').map(set=>({id:set.resource.id,states:set.screenshots.map(image=>String(image.attributes.processingState??'UNKNOWN'))}))}));
    const metadataDrift:string[]=[];const screenshotDrift:string[]=[];const object=(value:unknown)=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};const prefix=`versions/macOS/${selected.version}`;const versionManifest=object(local.desired[`${prefix}/version.json`]);for(const field of ['copyright','releaseType'])if(Object.hasOwn(versionManifest,field)&&canonical(store.version.attributes[field])!==canonical(versionManifest[field]))metadataDrift.push(`version.${field}`);
    for(const locale of app.localizations){const info=object(local.desired[`info/${locale}.json`]);const liveInfo=store.appInfoLocalizations.find(item=>item.attributes.locale===locale);const infoWanted:Record<string,unknown>={...info,...(!Object.hasOwn(info,'privacyPolicyUrl')&&app.defaults?.privacyPolicyUrl?{privacyPolicyUrl:app.defaults.privacyPolicyUrl}:{})};for(const field of ['name','subtitle','privacyPolicyUrl'])if(Object.hasOwn(infoWanted,field)&&canonical(liveInfo?.attributes[field])!==canonical(infoWanted[field]))metadataDrift.push(`info:${locale}.${field}`);
      const localPath=`${prefix}/localizations/${locale}`;const metadata=object(local.desired[`${localPath}/metadata.json`]);const liveText=store.versionLocalizations.find(item=>item.attributes.locale===locale);const defaults=object(versionManifest.defaults);const wanted:Record<string,unknown>={...metadata,...(!Object.hasOwn(metadata,'supportUrl')&&typeof defaults.supportUrl==='string'?{supportUrl:defaults.supportUrl}:{})};for(const [filename,field] of Object.entries({'description.txt':'description','keywords.txt':'keywords','promotional-text.txt':'promotionalText','whats-new.txt':'whatsNew'}))if(Object.hasOwn(local.desired,`${localPath}/${filename}`))wanted[field]=local.desired[`${localPath}/${filename}`];for(const field of ['supportUrl','marketingUrl','description','keywords','promotionalText','whatsNew'])if(Object.hasOwn(wanted,field)&&canonical(liveText?.attributes[field])!==canonical(wanted[field]))metadataDrift.push(`text:${locale}.${field}`);
      const manifest=object(local.desired[`${localPath}/screenshots.json`]);const expected=(object(manifest.sets).APP_DESKTOP as string[]|undefined);const remote=store.screenshotSets[liveText?.id??'']?.filter(set=>set.resource.attributes.screenshotDisplayType==='APP_DESKTOP')??[];if(!expected?.length)screenshotDrift.push(`${locale}: missing nonempty APP_DESKTOP manifest`);else if(remote.length!==1)screenshotDrift.push(`${locale}: expected one APP_DESKTOP set`);else {const order=(await this.api.list<unknown>(`/v1/appScreenshotSets/${remote[0]!.resource.id}/relationships/appScreenshots`,signal)).map(raw=>resource({...raw as object,attributes:{}},'appScreenshots',[]).id);if(new Set(order).size!==order.length||order.length!==remote[0]!.screenshots.length)screenshotDrift.push(`${locale}: screenshot order relationship is incomplete`);const actual=order.map(id=>remote[0]!.screenshots.find(image=>image.id===id)).filter(item=>item!==undefined);if(actual.length!==expected.length)screenshotDrift.push(`${locale}: screenshot count differs`);else for(let index=0;index<expected.length;index++)if(local.images[expected[index]!]===undefined||String(actual[index]!.attributes.sourceFileChecksum??'').toLowerCase()!==local.images[expected[index]!]!.md5.toLowerCase())screenshotDrift.push(`${locale}: screenshot ${index+1} bytes or order differ`);}}
    let reviewDrift=true;if(local.valid){const reviewAdapter=new MetadataAdapter({root:selected.root,platform:'macOS',version:selected.version,locales:app.localizations,domains:['review'],manageCategories:false},this.roots,this.api,()=>store.credentialContext);reviewDrift=await reviewAdapter.reviewDrift(signal);}
    const release:ReleaseState={appId:store.app.id,bundleId:app.app.bundleId,versionId:store.version.id,versionState:String(store.version.attributes.appVersionState??store.version.attributes.appStoreState??'UNKNOWN'),releaseType:String(store.version.attributes.releaseType??'UNKNOWN'),earliestReleaseDate:typeof store.version.attributes.earliestReleaseDate==='string'?store.version.attributes.earliestReleaseDate:null,build:{id:build.id,buildNumber:build.attributes.version,processingState:build.attributes.processingState,expired:build.attributes.expired,usesNonExemptEncryption:typeof build.attributes.usesNonExemptEncryption==='boolean'?build.attributes.usesNonExemptEncryption:null,appId:buildApp.id,platform:String(pre.attributes.platform),version:String(pre.attributes.version)},currentBuildId,locales,review:store.review??null,reviewDrift,submissions:submissions.sort((a,b)=>a.id.localeCompare(b.id,'en')),commerce:commerceAdapter.summary(commerceSnapshot),commercePriceDrift:commerceAdapter.propose(commerceSnapshot).some(operation=>operation.key==='price'),metadataDrift:metadataDrift.sort(),screenshotDrift:screenshotDrift.sort()};
    return {root:await realpath(selected.root),app,local,release,checks:releaseReadinessChecks(local,app,release),credentialContext:store.credentialContext};
  }
}

export class SubmissionAdapter implements Adapter {
  readonly domain='submission';#last:ReleaseSnapshot|undefined;#checks:ReadinessCheck[]|undefined;readonly #before=new Map<string,ReleaseState>();
  constructor(private readonly selection:SubmissionSelection,private readonly reader:SubmissionReader,private readonly api:ApiClient){}
  async capture(signal?:AbortSignal):Promise<ReleaseSnapshot>{const value=await this.reader.read(signal);const selected=submissionSelection.parse(this.selection);const blocked=value.checks.filter(check=>check.status==='blocked');if(blocked.length)throw new AppStoreError('releaseBlocked',`Release readiness is blocked by: ${blocked.map(check=>check.name).join(', ')}.`);this.#checks??=structuredClone(value.checks);const snapshot:ReleaseSnapshot={root:value.root,target:{appId:value.release.appId,bundleId:value.release.bundleId,platform:value.release.build.platform,version:value.release.build.version,buildId:value.release.build.id},credentialContext:value.credentialContext,inputs:value.local.hashes,secretFingerprint:value.local.secretFingerprint,rulesVersion:'submission-1',remote:{release:value.release as unknown as Json},checks:structuredClone(this.#checks),confirmations:selected.manualConfirmations};this.#last=structuredClone(snapshot);return snapshot;}
  summary(snapshot:Snapshot):Json {const value=snapshot as ReleaseSnapshot;const release=value.remote.release as unknown as ReleaseState;const flow=active(release);return {checks:value.checks as unknown as Json,selectedBuild:{id:release.build.id,buildNumber:release.build.buildNumber,processingState:release.build.processingState},releaseBehavior:{releaseType:release.releaseType,earliestReleaseDate:release.earliestReleaseDate,warning:releaseWarning(release)},existingSubmission:flow.submitted?{id:flow.submitted.id,state:flow.submitted.state}:null};}
  propose(snapshot:Snapshot):Operation[]{const release=snapshot.remote.release as unknown as ReleaseState;const flow=active(release);if(flow.conflict)throw new AppStoreError('submissionConflict',flow.conflict);if(flow.submitted){if(['WAITING_FOR_REVIEW','IN_REVIEW','COMPLETING','COMPLETE'].includes(flow.submitted.state))return [];throw new AppStoreError('submissionConflict',`Existing submission is in unsupported state ${flow.submitted.state}.`);}const operations:Operation[]=[];let dependencies:string[]=[];const add=(action:string,before:Json,after:Json)=>{const op:Operation={id:operationId(action),domain:this.domain,kind:'submission',key:'release',scope:`${release.build.platform} ${release.build.version}; ${releaseWarning(release)}`,before,after,dependencies:[...dependencies],affects:['release'],sensitive:false,payload:{action}};operations.push(op);dependencies=[op.id];};if(release.currentBuildId!==release.build.id)add('selectBuild',release.currentBuildId,{buildId:release.build.id});if(!flow.draft)add('createSubmission',{submissionIds:release.submissions.map(item=>item.id)},{appId:release.appId,platform:release.build.platform});if(!flow.draft?.items.some(item=>item.versionId===release.versionId))add('createItem',(flow.draft?.items??[]) as unknown as Json,{versionId:release.versionId});add('submit',flow.draft?.state??null,{submitted:true,releaseType:release.releaseType});return operations;}
  async execute(operation:Readonly<Operation>,signal?:AbortSignal):Promise<void>{const previous=this.#last;const snapshot=await this.capture(signal);if(!previous||canonical(previous)!==canonical(snapshot))throw new AppStoreError('stalePlan','Release inputs or live state changed immediately before submission dispatch.');const release=snapshot.remote.release as unknown as ReleaseState;this.#before.set(operation.id,structuredClone(release));const action=(operation.payload as {action:string}).action;const draft=active(release).draft;
    if(action==='selectBuild')await this.api.request(`/v1/appStoreVersions/${release.versionId}/relationships/build`,{method:'PATCH',body:{data:{type:'builds',id:release.build.id}},...(signal?{signal}:{})});
    else if(action==='createSubmission')await this.api.request('/v1/reviewSubmissions',{method:'POST',body:{data:{type:'reviewSubmissions',attributes:{platform:release.build.platform},relationships:{app:{data:{type:'apps',id:release.appId}}}}},...(signal?{signal}:{})});
    else if(action==='createItem'){if(!draft)throw new AppStoreError('missingDependency','Compatible draft submission must be verified first.');await this.api.request('/v1/reviewSubmissionItems',{method:'POST',body:{data:{type:'reviewSubmissionItems',relationships:{reviewSubmission:{data:{type:'reviewSubmissions',id:draft.id}},appStoreVersion:{data:{type:'appStoreVersions',id:release.versionId}}}}},...(signal?{signal}:{})});}
    else {if(!draft||draft.items.length!==1||draft.items[0]!.versionId!==release.versionId)throw new AppStoreError('submissionConflict','Submit only the exact draft containing the selected version item.');await this.api.request(`/v1/reviewSubmissions/${draft.id}`,{method:'PATCH',body:{data:{type:'reviewSubmissions',id:draft.id,attributes:{submitted:true}}},...(signal?{signal}:{})});}
  }
  verify(operation:Readonly<Operation>,snapshot:Snapshot):boolean{const before=this.#before.get(operation.id);const after=(snapshot.remote.release as unknown as ReleaseState);if(!before)return false;const action=(operation.payload as {action:string}).action;
    if(action==='selectBuild')return after.currentBuildId===after.build.id&&canonical({...before,currentBuildId:after.build.id})===canonical(after);
    if(action==='createSubmission'){const prior=new Set(before.submissions.map(item=>item.id));const created=after.submissions.filter(item=>!prior.has(item.id));return created.length===1&&created[0]!.platform===after.build.platform&&created[0]!.state==='READY_FOR_REVIEW'&&created[0]!.items.length===0&&canonical(before.submissions)===canonical(after.submissions.filter(item=>item.id!==created[0]!.id))&&canonical({...before,submissions:after.submissions})===canonical(after);}
    if(action==='createItem'){const prior=active(before).draft;const current=active(after).draft;if(!prior||!current||prior.id!==current.id)return false;const newItems=current.items.filter(item=>!prior.items.some(old=>old.id===item.id));return newItems.length===1&&newItems[0]!.versionId===after.versionId&&newItems[0]!.state==='READY_FOR_REVIEW'&&canonical({...prior,items:current.items})===canonical(current)&&canonical({...before,submissions:after.submissions})===canonical(after);}
    const prior=active(before).draft;const submitted=after.submissions.find(item=>item.id===prior?.id);return !!prior&&!!submitted&&['WAITING_FOR_REVIEW','IN_REVIEW','COMPLETING','COMPLETE'].includes(submitted.state)&&submitted.items.length===1&&submitted.items[0]!.versionId===after.versionId&&canonical({...before,versionState:after.versionState,submissions:after.submissions})===canonical(after);
  }
  remoteIds(operation:Readonly<Operation>,snapshot:Snapshot):string[]{const release=snapshot.remote.release as unknown as ReleaseState;const action=(operation.payload as {action:string}).action;if(action==='selectBuild')return [release.build.id];const flow=active(release);if(action==='createSubmission'||action==='submit')return flow.draft?[flow.draft.id]:flow.submitted?[flow.submitted.id]:[];if(action==='createItem')return flow.draft?.items.filter(item=>item.versionId===release.versionId).map(item=>item.id)??[];return [];}
}
