import type {ApiClient,ApiDocument} from '../api/client.js';
import {createHash,X509Certificate} from 'node:crypto';
import {resource} from '../api/resources/discovery.js';
import {AppStoreError} from '../errors.js';

export const certificateTypes=['DEVELOPMENT','DISTRIBUTION','IOS_DEVELOPMENT','IOS_DISTRIBUTION','MAC_APP_DISTRIBUTION','MAC_INSTALLER_DISTRIBUTION','MAC_APP_DEVELOPMENT','DEVELOPER_ID_APPLICATION','DEVELOPER_ID_APPLICATION_G2'] as const;
export const profileTypes=['IOS_APP_DEVELOPMENT','IOS_APP_STORE','IOS_APP_ADHOC','IOS_APP_INHOUSE','MAC_APP_DEVELOPMENT','MAC_APP_STORE','MAC_APP_DIRECT','TVOS_APP_DEVELOPMENT','TVOS_APP_STORE','TVOS_APP_ADHOC','TVOS_APP_INHOUSE','MAC_CATALYST_APP_DEVELOPMENT','MAC_CATALYST_APP_STORE','MAC_CATALYST_APP_DIRECT'] as const;
export const platforms=['IOS','MAC_OS','UNIVERSAL'] as const;
type Attributes=Record<string,string|number|boolean|null>;
export interface CertificateRecord{id:string;name:string;certificateType:string;platform:string;expirationDate:string;activated:boolean;serialFingerprint:string;publicKeyFingerprint:string|null}
export interface DeviceRecord{id:string;name:string;platform:string;udid:string;deviceClass:string;status:string;model:string;addedDate:string}
export interface ProfileRecord{id:string;name:string;platform:string;profileType:string;profileState:string;uuid:string;createdDate:string;expirationDate:string;bundleId:string;certificateIds:string[];deviceIds:string[]}
function exactString(attributes:Attributes,key:string,pattern:RegExp,max=500):string {const value=attributes[key];if(typeof value!=='string'||value.length>max||!pattern.test(value))throw new AppStoreError('incompleteSnapshot','Provisioning resource metadata is incomplete or malformed.');return value;}
function relation(raw:unknown,key:string,type:string):string {return resource({...((raw as {relationships?:Record<string,{data?:unknown}>}).relationships?.[key]?.data as object),attributes:{}},type,[]).id;}
function relations(raw:unknown,key:string,type:string):string[]{const data=(raw as {relationships?:Record<string,{data?:unknown}>}).relationships?.[key]?.data;if(!Array.isArray(data)||data.length>500)throw new AppStoreError('incompleteSnapshot','Provisioning relationships are missing or too large.');const ids=data.map(item=>resource({...item as object,attributes:{}},type,[]).id);if(new Set(ids).size!==ids.length)throw new AppStoreError('incompleteSnapshot','Provisioning relationships contain duplicates.');return ids.sort();}
export async function provisioningInventory(api:ApiClient,signal?:AbortSignal):Promise<{certificates:CertificateRecord[];devices:DeviceRecord[];profiles:ProfileRecord[]}>{
  const certs=await api.list<unknown>('/v1/certificates',signal);const devices=await api.list<unknown>('/v1/devices',signal);const profiles=await api.list<unknown>('/v1/profiles?include=bundleId,certificates,devices',signal);
  if(certs.length>1000||devices.length>10000||profiles.length>1000)throw new AppStoreError('incompleteSnapshot','Provisioning inventory exceeds the supported bounded account size.');
  const certificates=certs.map(raw=>{const item=resource(raw,'certificates',['name','certificateType','platform','expirationDate','activated','serialNumber','certificateContent']);const a=item.attributes;if(typeof a.activated!=='boolean')throw new AppStoreError('incompleteSnapshot','Certificate activation state is unavailable.');let publicKeyFingerprint:string|null=null;if(typeof a.certificateContent==='string'){if(a.certificateContent.length>128*1024||!/^[A-Za-z0-9+/]+={0,2}$/.test(a.certificateContent))throw new AppStoreError('incompleteSnapshot','Certificate content is malformed.');try{const certificate=new X509Certificate(Buffer.from(a.certificateContent,'base64'));publicKeyFingerprint=createHash('sha256').update(certificate.publicKey.export({format:'der',type:'spki'})).digest('hex');}catch{throw new AppStoreError('incompleteSnapshot','Certificate content cannot establish its public key identity.');}}return {id:item.id,name:exactString(a,'name',/^.{1,200}$/),certificateType:exactString(a,'certificateType',/^[A-Z_]+$/),platform:exactString(a,'platform',/^[A-Z_]+$/),expirationDate:exactString(a,'expirationDate',/^\d{4}-\d{2}-\d{2}T/),activated:a.activated,serialFingerprint:exactString(a,'serialNumber',/^[A-Fa-f0-9:]+$/),publicKeyFingerprint};});
  const deviceRecords=devices.map(raw=>{const item=resource(raw,'devices',['name','platform','udid','deviceClass','status','model','addedDate']);const a=item.attributes;return {id:item.id,name:exactString(a,'name',/^.{1,200}$/),platform:exactString(a,'platform',/^[A-Z_]+$/),udid:exactString(a,'udid',/^[A-Za-z0-9-]{8,100}$/),deviceClass:exactString(a,'deviceClass',/^[A-Z_]+$/),status:exactString(a,'status',/^(ENABLED|DISABLED)$/),model:exactString(a,'model',/^.{1,200}$/),addedDate:exactString(a,'addedDate',/^\d{4}-\d{2}-\d{2}T/)};});
  const profileRecords=profiles.map(raw=>{const item=resource(raw,'profiles',['name','platform','profileType','profileState','uuid','createdDate','expirationDate']);const a=item.attributes;return {id:item.id,name:exactString(a,'name',/^.{1,200}$/),platform:exactString(a,'platform',/^[A-Z_]+$/),profileType:exactString(a,'profileType',/^[A-Z_]+$/),profileState:exactString(a,'profileState',/^(ACTIVE|INVALID)$/),uuid:exactString(a,'uuid',/^[A-Fa-f0-9-]{8,100}$/),createdDate:exactString(a,'createdDate',/^\d{4}-\d{2}-\d{2}T/),expirationDate:exactString(a,'expirationDate',/^\d{4}-\d{2}-\d{2}T/),bundleId:relation(raw,'bundleId','bundleIds'),certificateIds:relations(raw,'certificates','certificates'),deviceIds:relations(raw,'devices','devices')};});
  for(const collection of [certificates,deviceRecords,profileRecords])if(new Set(collection.map(item=>item.id)).size!==collection.length)throw new AppStoreError('incompleteSnapshot','Provisioning inventory contains duplicate resource IDs.');
  return {certificates:certificates.sort((a,b)=>a.id.localeCompare(b.id,'en')),devices:deviceRecords.sort((a,b)=>a.id.localeCompare(b.id,'en')),profiles:profileRecords.sort((a,b)=>a.id.localeCompare(b.id,'en'))};
}

export async function downloadContent(api:ApiClient,family:'certificate'|'profile',id:string,signal?:AbortSignal):Promise<Buffer>{
  const type=family==='certificate'?'certificates':'profiles';const field=family==='certificate'?'certificateContent':'profileContent';
  const doc=await api.request<ApiDocument>(`/v1/${type}/${id}`,signal?{signal}:{});const item=resource(doc?.data,type,[field]);if(item.id!==id||typeof item.attributes[field]!=='string')throw new AppStoreError('artifactUnavailable','Requested signing artifact content is unavailable.');
  const encoded=item.attributes[field] as string;if(encoded.length>16*1024*1024||!/^[A-Za-z0-9+/]+={0,2}$/.test(encoded))throw new AppStoreError('artifactUnavailable','Signing artifact encoding is invalid or too large.');const bytes=Buffer.from(encoded,'base64');if(!bytes.length||bytes.toString('base64')!==encoded)throw new AppStoreError('artifactUnavailable','Signing artifact is not canonical base64.');return bytes;
}
